name: allocator.h tests

on:
    push:
        branches: [ main ]

jobs:

    test_allocator_linux:

        name: Build and test allocators [Linux]
        runs-on: ubuntu-latest

        # ====================
        #  Core
        # ====================

        steps:

          - name: Checkout code
            uses: actions/checkout@v7

          - name: Update OS
            run: |
                sudo apt-get update
                sudo apt-get install -y make

        # ====================
        #  Arena
        # ====================

          - name: Test Arena
            working-directory: ./tests
            run: |
                make test TARGET_DIR=allocator TARGET_NAME=arena

          - name: Clean Arena
            working-directory: ./tests
            run: |
                make clean TARGET_DIR=allocator TARGET_NAME=arena

        # ====================
        #  Bump Allocator
        # ====================

          - name: Test Bump Allocator
            working-directory: ./tests
            run: |
                make test TARGET_DIR=allocator TARGET_NAME=bump

          - name: Clean Bump Allocator
            working-directory: ./tests
            run: |
                make clean TARGET_DIR=allocator TARGET_NAME=bump

        # ====================
        #  Pool
        # ====================

          - name: Test Pool
            working-directory: ./tests
            run: |
                make test TARGET_DIR=allocator TARGET_NAME=pool

          - name: Clean Pool
            working-directory: ./tests
            run: |
                make clean TARGET_DIR=allocator TARGET_NAME=pool

    test_allocator_macos:

        name: Build and test allocators [MacOs]
        runs-on: macos-latest

        # ====================
        #  Core
        # ====================

        steps:

          - name: Checkout code
            uses: actions/checkout@v7

          - name: Get gcc
            run: |
                brew install gcc

        # ====================
        #  Arena
        # ====================

          - name: Test Arena
            working-directory: ./tests
            run: |
                make test TARGET_DIR=allocator TARGET_NAME=arena

          - name: Clean Arena
            working-directory: ./tests
            run: |
                make clean TARGET_DIR=allocator TARGET_NAME=arena

        # ====================
        #  Bump Allocator
        # ====================

          - name: Test Bump Allocator
            working-directory: ./tests
            run: |
                make test TARGET_DIR=allocator TARGET_NAME=bump

          - name: Clean Bump Allocator
            working-directory: ./tests
            run: |
                make clean TARGET_DIR=allocator TARGET_NAME=bump

        # ====================
        #  Pool
        # ====================

          - name: Test Pool
            working-directory: ./tests
            run: |
                make test TARGET_DIR=allocator TARGET_NAME=pool

          - name: Clean Pool
            working-directory: ./tests
            run: |
                make clean TARGET_DIR=allocator TARGET_NAME=pool

    test_allocator_windows:

        name: Build and test allocators [Windows]
        runs-on: windows-latest
        defaults:
            run:
                shell: msys {0}

        # ====================
        #  Core
        # ====================

        steps:

          - name: Checkout code
            uses: actions/checkout@v7

          - name: Setup MSYS2 and MinGW
            uses: msys2/setup-msys2@v2
            with:
                msystem: UCRT64
                update: true
                install: >-
                    mingw-w64-ucrt-x86_64-gcc
                    mingw-w64-ucrt-x86_64-make

        # ====================
        #  Arena
        # ====================

          - name: Test Arena
            working-directory: ./tests
            run: |
                make test TARGET_DIR=allocator TARGET_NAME=arena

          - name: Clean Arena
            working-directory: ./tests
            run: |
                make clean TARGET_DIR=allocator TARGET_NAME=arena

        # ====================
        #  Bump Allocator
        # ====================

          - name: Test Bump Allocator
            working-directory: ./tests
            run: |
                make test TARGET_DIR=allocator TARGET_NAME=bump

          - name: Clean Bump Allocator
            working-directory: ./tests
            run: |
                make clean TARGET_DIR=allocator TARGET_NAME=bump

        # ====================
        #  Pool
        # ====================

          - name: Test Pool
            working-directory: ./tests
            run: |
                make test TARGET_DIR=allocator TARGET_NAME=pool

          - name: Clean Pool
            working-directory: ./tests
            run: |
                make clean TARGET_DIR=allocator TARGET_NAME=pool